name: supervision_env_2
channels:
  - defaults
  - conda-forge  # Additional channel for more packages
dependencies:
  - python=3.8  # Downgraded to Python 3.8 for wider compatibility
  - numpy
  - xarray
  - pandas
  - matplotlib
  - xesmf
